In [40]:
import numpy as np
import random, string
from collections import Counter, OrderedDict
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
import numpy as np

In [41]:
class Task(object):
    def __init__(self, max_len=10, vocab_size=3, batch_size=5):
        self.vocab_size = vocab_size
        self.max_len = max_len
        self.universe = string.ascii_uppercase[0:self.vocab_size]
        alphabet_list = list(self.universe)
        self.label_encoder = LabelEncoder()
        numeric_labels = self.label_encoder.fit_transform(alphabet_list)
        numeric_labels = numeric_labels.reshape(-1, 1)
        self.one_hot_encoder = OneHotEncoder(sparse_output=False)
        self.one_hot_encoder.fit(numeric_labels)
        self.batch_size = batch_size

    def next_batch(self):
        x_batch = []
        y_batch = []
        for b in range(0, self.batch_size):
            alphabets = []
            for i in range(self.max_len):
                alphabets.append(random.choice(self.universe))
                # alphabets.append(random.randint(1,self.vocab_size))
            count_alphabets = Counter(alphabets)
            m = dict(count_alphabets.most_common())
            #print('x', alphabets)
            numeric_labels = self.label_encoder.transform(alphabets)
            numeric_labels = numeric_labels.reshape(-1, 1)
            #print('x numeric', numeric_labels)
            x = self.one_hot_encoder.transform(numeric_labels)
            #print('x one hot', x)
            y = [[m.get(k, 0)] for k in self.universe]
            #print('y', y)
            x_batch.append(x)
            y_batch.append(y)
            #print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')
        return torch.tensor(x_batch, dtype=torch.float),torch.tensor(y_batch, dtype=torch.float)


In [42]:
task = Task(max_len=5,vocab_size=3, batch_size=8)

In [50]:
x, y = task.next_batch()

In [51]:
x.shape

torch.Size([8, 5, 3])

In [52]:
x1 = x.squeeze(2)
x1.shape

torch.Size([8, 5, 3])

In [36]:
y

tensor([[[2.],
         [2.],
         [1.]],

        [[0.],
         [2.],
         [3.]],

        [[3.],
         [0.],
         [2.]],

        [[0.],
         [3.],
         [2.]],

        [[3.],
         [1.],
         [1.]],

        [[3.],
         [1.],
         [1.]],

        [[2.],
         [3.],
         [0.]],

        [[2.],
         [1.],
         [2.]]])

In [34]:
y.shape

torch.Size([8, 3, 1])

In [35]:
y[0]

tensor([[2.],
        [2.],
        [1.]])

In [39]:
y.argmax(dim=0)

tensor([[2],
        [3],
        [1]])

In [38]:
y

tensor([[[2.],
         [2.],
         [1.]],

        [[0.],
         [2.],
         [3.]],

        [[3.],
         [0.],
         [2.]],

        [[0.],
         [3.],
         [2.]],

        [[3.],
         [1.],
         [1.]],

        [[3.],
         [1.],
         [1.]],

        [[2.],
         [3.],
         [0.]],

        [[2.],
         [1.],
         [2.]]])